# Generated by Django 5.2.1 on 2025-11-03 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш файла')),
                ('directory', models.CharField(max_length=255, verbose_name='Директория')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён ли')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя тега')),
                ('files', models.ManyToManyField(related_name='tags', to='db.anyfile')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.tag')),
            ],
        ),
    ]
