# Generated by Django 5.2.6 on 2026-01-01 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anyfile',
            name='isarchive',
            field=models.BooleanField(default=False, verbose_name='Флаг архива'),
        ),
        migrations.AddField(
            model_name='anyfile',
            name='mediagroup',
            field=models.IntegerField(choices=[(1, 'Книга'), (2, 'Картинка'), (3, 'Аудио')], default=1, verbose_name='Тип файла'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_fields', models.JSONField(default=dict, verbose_name='Прочие поля')),
                ('title', models.CharField(blank=True, default='', verbose_name='Заголовок')),
                ('isbn', models.CharField(blank=True, default='', verbose_name='ISBN')),
                ('public_year', models.CharField(blank=True, default='', verbose_name='Год издания')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='db.anyfile')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
