# Generated by Django 5.2.1 on 2026-07-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш файла')),
                ('directory', models.CharField(max_length=255, verbose_name='Директория')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён ли')),
                ('mediagroup', models.IntegerField(choices=[(1, 'Документ'), (2, 'Картинка'), (3, 'Аудио')], default=1, verbose_name='Тип файла')),
                ('isarchive', models.BooleanField(default=False, verbose_name='Флаг архива')),
                ('tags', models.ManyToManyField(related_name='files', to='common.tag')),
            ],
        ),
    ]
