# Generated by Django 5.2.1 on 2026-09-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('mediagarden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш файла')),
                ('directory', models.CharField(max_length=255, verbose_name='Директория')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён ли')),
                ('isarchive', models.BooleanField(default=False, verbose_name='Флаг архива')),
                ('tags', models.ManyToManyField(related_name='audios', to='base.tag')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш файла')),
                ('directory', models.CharField(max_length=255, verbose_name='Директория')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён ли')),
                ('isarchive', models.BooleanField(default=False, verbose_name='Флаг архива')),
                ('tags', models.ManyToManyField(related_name='documents', to='base.tag')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='PictureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш файла')),
                ('directory', models.CharField(max_length=255, verbose_name='Директория')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён ли')),
                ('isarchive', models.BooleanField(default=False, verbose_name='Флаг архива')),
                ('tags', models.ManyToManyField(related_name='pictures', to='base.tag')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш файла')),
                ('directory', models.CharField(max_length=255, verbose_name='Директория')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён ли')),
                ('isarchive', models.BooleanField(default=False, verbose_name='Флаг архива')),
                ('tags', models.ManyToManyField(related_name='videos', to='base.tag')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.DeleteModel(
            name='AnyFile',
        ),
    ]
